
### get foods index
GET http://localhost:3000/foods.json

### post foods create
POST http://localhost:3000/foods.json
Content-Type: application/json

{
"meal": "dinner",
"style": "linguini_with_peanut_sauce",
"size": "large",
"description": "pasta with linguini peanut sauce"
}


### get foods show
GET http://localhost:3000/foods/9.json

### patch food update
PATCH http://localhost:3000/foods/8.json
Content-Type: application/json

{
"meal": "breakfast",
"style": "spinach_craoissant",
"size": "medium",
"description": "spinach croissant"
}

### delete foods destroy
DELETE http://localhost:3000/foods/5.json
